/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Certifications = {
  _id: string
  _type: 'certifications'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  certificationsBlocks?: Array<{
    title?: string
    description?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    _type: 'certificationBlock'
    _key: string
  }>
}

export type Remedies = {
  _id: string
  _type: 'remedies'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  firstDescription?: string
  dualImage?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  secodDescription?: string
  benefits?: Array<{
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    description?: string
    _type: 'benefit'
    _key: string
  }>
}

export type Property = {
  _id: string
  _type: 'property'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  featuredProduct?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'product'
  }
  featuredImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type JustAFlower = {
  _id: string
  _type: 'justAFlower'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  mainImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  quote?: string
  text?: string
  video?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
  secondaryText?: string
  SecondaryQuote?: string
  tertiaryText?: string
  tertiaryImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  tetratiaryText?: string
  tetraciaryQuote?: string
}

export type ResellerForm = {
  _id: string
  _type: 'resellerForm'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName?: string
  lastName?: string
  email?: string
  nie?: string
  province?:
    | '\xC1lava'
    | 'Albacete'
    | 'Alicante'
    | 'Almer\xEDa'
    | 'Asturias'
    | '\xC1vila'
    | 'Badajoz'
    | 'Baleares'
    | 'Barcelona'
    | 'Burgos'
    | 'C\xE1ceres'
    | 'C\xE1diz'
    | 'Cantabria'
    | 'Castell\xF3n'
    | 'Ceuta'
    | 'Ciudad Real'
    | 'C\xF3rdoba'
    | 'Cuenca'
    | 'Gerona'
    | 'Granada'
    | 'Guadalajara'
    | 'Guip\xFAzcoa'
    | 'Huelva'
    | 'Huesca'
    | 'Ja\xE9n'
    | 'La Coru\xF1a'
    | 'La Rioja'
    | 'Las Palmas'
    | 'Le\xF3n'
    | 'L\xE9rida'
    | 'Lugo'
    | 'Madrid'
    | 'M\xE1laga'
    | 'Melilla'
    | 'Murcia'
    | 'Navarra'
    | 'Orense'
    | 'Palencia'
    | 'Pontevedra'
    | 'Salamanca'
    | 'Santa Cruz de Tenerife'
    | 'Segovia'
    | 'Sevilla'
    | 'Soria'
    | 'Tarragona'
    | 'Teruel'
    | 'Toledo'
    | 'Valencia'
    | 'Valladolid'
    | 'Vizcaya'
    | 'Zamora'
    | 'Zaragoza'
  phone?: string
  birthDate?: string
  privacyPolicy?: boolean
  jobType?:
    | 'Aut\xF3nomo'
    | 'Tienda Online'
    | 'Tienda F\xEDsica'
    | 'Distribuidor'
  companyFile?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
}

export type Purchase = {
  _id: string
  _type: 'purchase'
  _createdAt: string
  _updatedAt: string
  _rev: string
  userEmail?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'user'
  }
  reseller?: boolean
  products?: Array<{
    product?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'product'
    }
    quantity?: number
    _key: string
  }>
  totalAmount?: number
  purchaseDate?: string
  paymentMethod?: string
  status?:
    | 'pendiente'
    | 'completado'
    | 'cancelado'
    | 'procesando'
    | 'enviado'
    | 'entregado'
  shippingAddress?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'shippingAddress'
  }
}

export type ShippingAddress = {
  _id: string
  _type: 'shippingAddress'
  _createdAt: string
  _updatedAt: string
  _rev: string
  address?: {
    street?: string
    floor?: string
    reference?: string
    country?: string
    postal_code?: string
    locality?: string
  }
  purchase?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'purchase'
  }>
}

export type User = {
  _id: string
  _type: 'user'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  email?: string
  password?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  idDocument?: {
    type?: 'DNI' | 'NIE' | 'NIF'
    value?: string
  }
  phone?: string
  address?: {
    street?: string
    floor?: string
    reference?: string
    country?:
      | 'Alemania'
      | 'Austria'
      | 'B\xE9lgica'
      | 'Bulgaria'
      | 'Chipre'
      | 'Croacia'
      | 'Dinamarca'
      | 'Eslovaquia'
      | 'Eslovenia'
      | 'Espa\xF1a'
      | 'Estonia'
      | 'Finlandia'
      | 'Francia'
      | 'Grecia'
      | 'Hungr\xEDa'
      | 'Irlanda'
      | 'Italia'
      | 'Letonia'
      | 'Lituania'
      | 'Luxemburgo'
      | 'Malta'
      | 'Pa\xEDses Bajos'
      | 'Polonia'
      | 'Portugal'
      | 'Rep\xFAblica Checa'
      | 'Ruman\xEDa'
      | 'Suecia'
      | 'Estados Unidos'
      | 'Canad\xE1'
    postal_code?: string
    locality?: string
  }
  shippingAddress?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'shippingAddress'
  }>
  reseller?: boolean
  discount?: number
}

export type SeoMetatags = {
  _id: string
  _type: 'seoMetatags'
  _createdAt: string
  _updatedAt: string
  _rev: string
  titleTemplate?: string
  defaultTitle?: string
  description?: string
  keywords?: Array<string>
  dominio?: string
  openGraph?: {
    url?: string
    images?: Array<{
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      width?: number
      height?: number
      _type: 'image'
      _key: string
    }>
  }
  twitter?: {
    images?: Array<{
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
      _key: string
    }>
  }
}

export type Prefooter = {
  _id: string
  _type: 'prefooter'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  link?: string
}

export type Newsletter = {
  _id: string
  _type: 'newsletter'
  _createdAt: string
  _updatedAt: string
  _rev: string
  email?: string
  date?: string
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  subtitle?: string
  logo?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  socialMedia?: Array<{
    platformName?: 'twitter' | 'instagram' | 'facebook' | 'youtube'
    link?: string
    _type: 'platform'
    _key: string
  }>
  contactInfo?: {
    email?: string
    phone?: string
    address?: string
  }
  copyright?: string
}

export type SalesPolicy = {
  _id: string
  _type: 'salesPolicy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type PrivacyPolicy = {
  _id: string
  _type: 'privacyPolicy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type CookiePolicy = {
  _id: string
  _type: 'cookiePolicy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  bentoThreeImages?: Array<{
    imageLink?: string
    bentoImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
      }
      _type: 'file'
    }
    _key: string
  }>
  bentofeaturedCategory?: {
    title?:
      | 'Bienestar'
      | 'Cosm\xE9tica corporal'
      | 'Cosm\xE9tica facial'
      | 'Esencias para lavado'
      | 'Higiene personal'
      | 'Hogar y ambiente'
      | 'L\xEDnea mosquitos e insectos'
    description?: string
  }
  bentoFeaturedProducto?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'product'
  }
  mainListCategories?: Array<
    | 'Bienestar'
    | 'Cosm\xE9tica corporal'
    | 'Cosm\xE9tica facial'
    | 'Esencias para lavado'
    | 'Higiene personal'
    | 'Hogar y ambiente'
    | 'L\xEDnea mosquitos e insectos'
  >
  InfoCards?: Array<{
    icon?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    title?: string
    description?: string
    _key: string
  }>
  carousel1?: {
    title?: string
    category?:
      | 'Bienestar'
      | 'Cosm\xE9tica corporal'
      | 'Cosm\xE9tica facial'
      | 'Esencias para lavado'
      | 'Higiene personal'
      | 'Hogar y ambiente'
      | 'L\xEDnea mosquitos e insectos'
  }
  carousel2?: {
    title?: string
    category?:
      | 'Bienestar'
      | 'Cosm\xE9tica corporal'
      | 'Cosm\xE9tica facial'
      | 'Esencias para lavado'
      | 'Higiene personal'
      | 'Hogar y ambiente'
      | 'L\xEDnea mosquitos e insectos'
  }
  featuredEvent?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'events'
  }
}

export type Events = {
  _id: string
  _type: 'events'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  date?: string
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  urls?: Array<{
    calendarName?: string
    calendarUrl?: string
    _key: string
  }>
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  nombre?: string
  descripcion?: string
  usabilidad?: string
  composicion?: string
  slogan?: string
  codigoReferencia?: string
  codigoBarras?: string
  precio?: number
  medidas?: {
    ancho?: number
    alto?: number
    profundidad?: number
    peso?: number
    volumen?: number
  }
  fotoPrincipal?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  fotosVarias?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  fichaTecnica?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
  stock?: number
  categoria?: string
  subcategoria?: string
  certificacion?: string
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Teams = {
  _id: string
  _type: 'teams'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  role?: string
  links?: Array<{
    title?: string
    url?: string
    _key: string
  }>
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  stats?: Array<{
    title?: string
    value?: string
    description?: string
    _key: string
  }>
  stats_image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  second_section_title?: string
  second_section_description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  teams_section_title?: string
  teams_section_description?: string
  teams?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'teams'
  }>
}

export type BlogArticles = {
  _id: string
  _type: 'blog-articles'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  mainImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  description?: string
  categories?: Array<string>
  featured?: boolean
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | Certifications
  | Remedies
  | Property
  | JustAFlower
  | ResellerForm
  | Purchase
  | ShippingAddress
  | User
  | SeoMetatags
  | Prefooter
  | Newsletter
  | Footer
  | SalesPolicy
  | PrivacyPolicy
  | CookiePolicy
  | HomePage
  | Events
  | Product
  | SanityFileAsset
  | Teams
  | AboutPage
  | BlogArticles
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | MediaTag
  | Slug
export declare const internalGroqTypeReferenceTo: unique symbol
